# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: electiondata.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'electiondata.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x65lectiondata.proto\"\xac\x01\n\x0c\x45lectionData\x12\x10\n\x08regionID\x18\x01 \x01(\t\x12\x12\n\nregionName\x18\x02 \x01(\t\x12\x15\n\rregionAddress\x18\x03 \x01(\t\x12\x18\n\x10regionPostalCode\x18\x04 \x01(\t\x12\x14\n\x0c\x66\x65\x64\x65ralState\x18\x05 \x01(\t\x12\x11\n\ttimestamp\x18\x06 \x01(\t\x12\x1c\n\x0c\x63ountingData\x18\x07 \x03(\x0b\x32\x06.Party\"K\n\x05Party\x12\x0f\n\x07partyID\x18\x01 \x01(\t\x12\x13\n\x0b\x61mountVotes\x18\x02 \x01(\x05\x12\x1c\n\x04vost\x18\x03 \x03(\x0b\x32\x0e.Vorzugsstimme\"F\n\rVorzugsstimme\x12\x14\n\x0clistenNummer\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x11\n\tvoteCount\x18\x03 \x01(\x05\"\"\n\x0eMessageRequest\x12\x10\n\x08regionID\x18\x01 \x01(\t\"6\n\x0fMessageResponse\x12#\n\x0cresponseData\x18\x01 \x01(\x0b\x32\r.ElectionData2F\n\x0c\x45lectiondata\x12\x36\n\x0fGetElectionData\x12\x0f.MessageRequest\x1a\x10.MessageResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'electiondata_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ELECTIONDATA']._serialized_start=23
  _globals['_ELECTIONDATA']._serialized_end=195
  _globals['_PARTY']._serialized_start=197
  _globals['_PARTY']._serialized_end=272
  _globals['_VORZUGSSTIMME']._serialized_start=274
  _globals['_VORZUGSSTIMME']._serialized_end=344
  _globals['_MESSAGEREQUEST']._serialized_start=346
  _globals['_MESSAGEREQUEST']._serialized_end=380
  _globals['_MESSAGERESPONSE']._serialized_start=382
  _globals['_MESSAGERESPONSE']._serialized_end=436
  _globals['_ELECTIONDATA']._serialized_start=438
  _globals['_ELECTIONDATA']._serialized_end=508
# @@protoc_insertion_point(module_scope)
